import type { Practitioner } from "./types";

// Demo dataset. All practitioners are FICTIONAL, generated to exercise the
// directory's filters, map, ranking, and empty states. In production this is
// replaced by the Postgres data layer (db/migrations/) populated by the
// Phase 1 migration of the existing prose directory content.
//
// Deliberate shape: lab-techs outnumber consultants roughly 2:1, mirroring
// the real network (~250 lab-techs vs ~100 consultants, PRD §1).

const MED = "Mediterranean Forests, Woodlands & Scrub";
const TBF = "Temperate Broadleaf & Mixed Forests";
const TGS = "Temperate Grasslands, Savannas & Shrublands";
const TMF = "Tropical & Subtropical Moist Broadleaf Forests";
const TGR = "Tropical & Subtropical Grasslands, Savannas & Shrublands";
const DXS = "Deserts & Xeric Shrublands";
const BOR = "Boreal Forests/Taiga";

export const PRACTITIONERS: Practitioner[] = [
  {
    id: "p01", slug: "elena-vasquez", displayName: "Elena Vásquez",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2019 }], certifiedSince: 2019,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 300,
    city: "Sevilla", adminArea: "Andalucía", countryCode: "ES", lat: 37.389, lng: -5.984,
    ecoregion: "Southwest Iberian Mediterranean sclerophyllous and mixed forests", biome: MED, realm: "Palearctic",
    crops: ["olive", "vineyard", "citrus"], soilTypes: ["calcareous", "clay"],
    languages: [{ slug: "es", proficiency: "native" }, { slug: "en", proficiency: "fluent" }],
    practices: ["compost_production", "transition_organic"],
    bio: "Elena grew up between her family's olive groves outside Écija and has spent six years helping Andalusian growers rebuild fungal networks in soils compacted by decades of tillage. Her work centres on dehesa systems, dry-farmed olives, and old-vine garnacha, with a particular interest in water retention on calcareous slopes. She runs a small on-farm compost operation and teaches seasonal workshops in Spanish and English.",
  },
  {
    id: "p02", slug: "mehmet-aydin", displayName: "Mehmet Aydın",
    roles: ["consultant", "lab_tech"], certifications: [{ program: "CC", year: 2021 }, { program: "LT", year: 2020 }], certifiedSince: 2020,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 250,
    city: "İzmir", adminArea: "Ege", countryCode: "TR", lat: 38.423, lng: 27.143,
    ecoregion: "Aegean and Western Turkey sclerophyllous and mixed forests", biome: MED, realm: "Palearctic",
    crops: ["vineyard", "olive", "vegetables"], soilTypes: ["calcareous", "sandy"],
    languages: [{ slug: "tr", proficiency: "native" }, { slug: "en", proficiency: "working" }],
    practices: ["microscopy", "compost_extracts"],
    bio: "Mehmet runs a microscopy lab in İzmir serving vineyards and olive growers across the Aegean coast. A former agronomist with the regional cooperative, he combines biological assessments with practical amendment plans that smallholders can execute without new machinery. He is one of the few practitioners offering full soil food web assessments in Turkish.",
  },
  {
    id: "p03", slug: "claire-dubois", displayName: "Claire Dubois",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2018 }], certifiedSince: 2018,
    acceptingClients: false, servicesRemotely: false, travelRadiusKm: 150,
    city: "Avignon", adminArea: "Provence", countryCode: "FR", lat: 43.949, lng: 4.806,
    ecoregion: "Northeastern Spain and Southern France Mediterranean forests", biome: MED, realm: "Palearctic",
    crops: ["vineyard", "orchard_fruit"], soilTypes: ["calcareous", "loam"],
    languages: [{ slug: "fr", proficiency: "native" }, { slug: "en", proficiency: "fluent" }, { slug: "es", proficiency: "working" }],
    practices: ["compost_production", "compost_extracts", "transition_organic"],
    bio: "Claire has guided over forty Rhône valley estates through biological transition, from first microscope assessment to certified organic status. Her waiting list is currently closed. She co-authors a regional newsletter on vineyard soil biology and mentors newly certified consultants in southern France.",
  },
  {
    id: "p04", slug: "sofia-lindqvist", displayName: "Sofia Lindqvist",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2022 }], certifiedSince: 2022,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 100,
    city: "Göteborg", adminArea: "Västra Götaland", countryCode: "SE", lat: 57.709, lng: 11.975,
    ecoregion: "Sarmatic mixed forests", biome: TBF, realm: "Palearctic",
    crops: ["vegetables", "cereals"], soilTypes: ["clay", "peat"],
    languages: [{ slug: "sv", proficiency: "native" }, { slug: "en", proficiency: "fluent" }],
    practices: ["microscopy"],
    bio: "Sofia offers microscope-based soil assessments for market gardens and grain farms across western Sweden, with remote sample analysis for the rest of Scandinavia. She came to soil biology from marine microbiology and brings a methodical sampling protocol that growers appreciate.",
  },
  {
    id: "p05", slug: "james-okafor", displayName: "James Okafor",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2020 }], certifiedSince: 2020,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: null,
    city: "Nairobi", adminArea: "Nairobi County", countryCode: "KE", lat: -1.286, lng: 36.817,
    ecoregion: "East African montane forests", biome: TMF, realm: "Afrotropic",
    crops: ["coffee", "tropical_smallholder", "vegetables"], soilTypes: ["volcanic", "clay"],
    languages: [{ slug: "en", proficiency: "native" }],
    practices: ["compost_production", "transition_organic"],
    bio: "James works with coffee cooperatives and smallholder vegetable growers across the Kenyan highlands, building compost programmes that use locally available feedstocks. He advises remotely across East Africa and has trained village-level compost teams serving over 800 farms.",
  },
  {
    id: "p06", slug: "ana-souza", displayName: "Ana Souza",
    roles: ["consultant", "lab_tech"], certifications: [{ program: "CC", year: 2022 }, { program: "LT", year: 2021 }], certifiedSince: 2021,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 400,
    city: "Campinas", adminArea: "São Paulo", countryCode: "BR", lat: -22.906, lng: -47.062,
    ecoregion: "Alto Paraná Atlantic forests", biome: TMF, realm: "Neotropic",
    crops: ["coffee", "citrus", "cereals"], soilTypes: ["clay", "loam"],
    languages: [{ slug: "pt", proficiency: "native" }, { slug: "es", proficiency: "fluent" }, { slug: "en", proficiency: "working" }],
    practices: ["microscopy", "compost_extracts", "transition_organic"],
    bio: "Ana splits her time between a soil biology lab in Campinas and consulting for coffee and citrus operations transitioning away from fumigation-heavy programmes. She works throughout southeastern Brazil and remotely across Latin America in Portuguese and Spanish.",
  },
  {
    id: "p07", slug: "rachel-whitfield", displayName: "Rachel Whitfield",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2017 }], certifiedSince: 2017,
    acceptingClients: true, servicesRemotely: false, travelRadiusKm: 500,
    city: "Paso Robles", adminArea: "California", countryCode: "US", lat: 35.627, lng: -120.691,
    ecoregion: "California montane chaparral and woodlands", biome: MED, realm: "Nearctic",
    crops: ["vineyard", "olive", "orchard_fruit"], soilTypes: ["calcareous", "sandy"],
    languages: [{ slug: "en", proficiency: "native" }, { slug: "es", proficiency: "working" }],
    practices: ["compost_production", "compost_extracts"],
    bio: "Rachel consults for Central Coast vineyards and olive ranches on biological soil management under drought. Her long-running trial blocks in Paso Robles comparing compost extract programmes against conventional fertigation are among the most cited practical datasets in the network.",
  },
  {
    id: "p08", slug: "priya-sharma", displayName: "Priya Sharma",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2023 }], certifiedSince: 2023,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 200,
    city: "Pune", adminArea: "Maharashtra", countryCode: "IN", lat: 18.52, lng: 73.856,
    ecoregion: "Deccan thorn scrub forests", biome: TGR, realm: "Indomalayan",
    crops: ["cereals", "vegetables", "tropical_smallholder"], soilTypes: ["clay", "saline"],
    languages: [{ slug: "hi", proficiency: "native" }, { slug: "en", proficiency: "fluent" }],
    practices: ["microscopy", "compost_production"],
    bio: "Priya runs biological assessments for farmer producer organisations across Maharashtra, focusing on sodic soil recovery in irrigated cereal systems. She accepts shipped samples from across India and reports in Hindi and English.",
  },
  {
    id: "p09", slug: "tom-bakker", displayName: "Tom Bakker",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2021 }], certifiedSince: 2021,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 150,
    city: "Wageningen", adminArea: "Gelderland", countryCode: "NL", lat: 51.969, lng: 5.665,
    ecoregion: "Atlantic mixed forests", biome: TBF, realm: "Palearctic",
    crops: ["vegetables", "turf"], soilTypes: ["sandy", "peat"],
    languages: [{ slug: "de", proficiency: "working" }, { slug: "en", proficiency: "fluent" }],
    practices: ["microscopy", "compost_extracts"],
    bio: "Tom assesses soils for Dutch glasshouse growers and sports turf managers, and analyses shipped samples from across northwestern Europe. His background is in plant pathology, which shapes his focus on disease-suppressive biology.",
  },
  {
    id: "p10", slug: "lucia-moreno", displayName: "Lucía Moreno",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2022 }], certifiedSince: 2022,
    acceptingClients: true, servicesRemotely: false, travelRadiusKm: 120,
    city: "Mendoza", adminArea: "Mendoza", countryCode: "AR", lat: -32.889, lng: -68.845,
    ecoregion: "Low Monte", biome: DXS, realm: "Neotropic",
    crops: ["vineyard", "orchard_fruit"], soilTypes: ["sandy", "saline"],
    languages: [{ slug: "es", proficiency: "native" }],
    practices: ["microscopy"],
    bio: "Lucía provides microscope assessments for Mendoza's irrigated vineyards, with particular experience in salinity-stressed blocks under flood irrigation. She works in Spanish and visits sites within the province.",
  },
  {
    id: "p11", slug: "david-crane", displayName: "David Crane",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2016 }], certifiedSince: 2016,
    acceptingClients: false, servicesRemotely: true, travelRadiusKm: 800,
    city: "Fargo", adminArea: "North Dakota", countryCode: "US", lat: 46.877, lng: -96.789,
    ecoregion: "Northern tall grasslands", biome: TGS, realm: "Nearctic",
    crops: ["cereals", "pasture"], soilTypes: ["clay", "loam"],
    languages: [{ slug: "en", proficiency: "native" }],
    practices: ["transition_organic", "compost_production"],
    bio: "David advises broadacre grain and grazing operations across the northern plains on reducing synthetic inputs through biological management. Currently at capacity; he maintains a waiting list and takes on new remote clients each spring.",
  },
  {
    id: "p12", slug: "hana-yilmaz", displayName: "Hana Yılmaz",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2023 }], certifiedSince: 2023,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 80,
    city: "Antalya", adminArea: "Akdeniz", countryCode: "TR", lat: 36.897, lng: 30.713,
    ecoregion: "Southern Anatolian montane conifer and deciduous forests", biome: MED, realm: "Palearctic",
    crops: ["citrus", "vegetables"], soilTypes: ["calcareous", "clay"],
    languages: [{ slug: "tr", proficiency: "native" }, { slug: "de", proficiency: "fluent" }],
    practices: ["microscopy", "compost_extracts"],
    bio: "Hana serves Antalya's protected-cropping vegetable sector and coastal citrus groves with biological assessments and brewing protocols. She grew up in Germany and works comfortably with the region's German-speaking export operations.",
  },
  {
    id: "p13", slug: "marcus-hale", displayName: "Marcus Hale",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2020 }], certifiedSince: 2020,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 300,
    city: "Perth", adminArea: "Western Australia", countryCode: "AU", lat: -31.95, lng: 115.86,
    ecoregion: "Southwest Australia woodlands", biome: MED, realm: "Australasia",
    crops: ["cereals", "vineyard", "pasture"], soilTypes: ["sandy", "saline"],
    languages: [{ slug: "en", proficiency: "native" }],
    practices: ["microscopy", "compost_production"],
    bio: "Marcus works the Western Australian wheatbelt and Margaret River vineyards, assessing biology in some of the world's oldest and most weathered soils. He accepts shipped samples nationally and runs field days on non-wetting sands.",
  },
  {
    id: "p14", slug: "ingrid-olsen", displayName: "Ingrid Olsen",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2021 }], certifiedSince: 2021,
    acceptingClients: false, servicesRemotely: true, travelRadiusKm: 200,
    city: "Trondheim", adminArea: "Trøndelag", countryCode: "NO", lat: 63.43, lng: 10.395,
    ecoregion: "Scandinavian and Russian taiga", biome: BOR, realm: "Palearctic",
    crops: ["vegetables", "pasture"], soilTypes: ["peat", "loam"],
    languages: [{ slug: "sv", proficiency: "fluent" }, { slug: "en", proficiency: "fluent" }],
    practices: ["microscopy"],
    bio: "Ingrid analyses soils for short-season vegetable growers and dairy pasture in central Norway. Currently on parental leave and not accepting new samples until next season.",
  },
  {
    id: "p15", slug: "carlos-mendez", displayName: "Carlos Méndez",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2021 }], certifiedSince: 2021,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 350,
    city: "Talca", adminArea: "Maule", countryCode: "CL", lat: -35.426, lng: -71.655,
    ecoregion: "Chilean Matorral", biome: MED, realm: "Neotropic",
    crops: ["vineyard", "orchard_fruit", "cereals"], soilTypes: ["clay", "volcanic"],
    languages: [{ slug: "es", proficiency: "native" }, { slug: "en", proficiency: "working" }],
    practices: ["compost_production", "transition_organic", "compost_extracts"],
    bio: "Carlos consults for wine and cherry producers through Chile's central valley, designing compost and extract programmes matched to volcanic-influenced soils. He advises remotely across the Spanish-speaking Americas.",
  },
  {
    id: "p16", slug: "amara-diallo", displayName: "Amara Diallo",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2022 }], certifiedSince: 2022,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 150,
    city: "Thiès", adminArea: "Thiès", countryCode: "SN", lat: 14.79, lng: -16.926,
    ecoregion: "West Sudanian savanna", biome: TGR, realm: "Afrotropic",
    crops: ["vegetables", "cereals", "tropical_smallholder"], soilTypes: ["sandy"],
    languages: [{ slug: "fr", proficiency: "native" }, { slug: "en", proficiency: "working" }],
    practices: ["microscopy", "compost_production"],
    bio: "Amara supports market-garden cooperatives in Senegal's Niayes zone with biological assessment and compost quality control, and consults remotely for francophone West Africa.",
  },
  {
    id: "p17", slug: "beth-oconnell", displayName: "Beth O'Connell",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2019 }], certifiedSince: 2019,
    acceptingClients: true, servicesRemotely: false, travelRadiusKm: 250,
    city: "Cork", adminArea: "Munster", countryCode: "IE", lat: 51.898, lng: -8.475,
    ecoregion: "Celtic broadleaf forests", biome: TBF, realm: "Palearctic",
    crops: ["pasture", "vegetables"], soilTypes: ["loam", "peat"],
    languages: [{ slug: "en", proficiency: "native" }],
    practices: ["microscopy", "compost_extracts"],
    bio: "Beth works with Irish dairy and drystock farms assessing pasture soil biology under high rainfall. She visits farms across Munster and runs microscopy evenings with local discussion groups.",
  },
  {
    id: "p18", slug: "kenji-watanabe", displayName: "Kenji Watanabe",
    roles: ["consultant"], certifications: [{ program: "CC", year: 2022 }], certifiedSince: 2022,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 200,
    city: "Nagano", adminArea: "Chūbu", countryCode: "JP", lat: 36.649, lng: 138.181,
    ecoregion: "Nihonkai montane deciduous forests", biome: TBF, realm: "Palearctic",
    crops: ["orchard_fruit", "vegetables", "cereals"], soilTypes: ["volcanic", "loam"],
    languages: [{ slug: "en", proficiency: "fluent" }],
    practices: ["compost_production", "transition_organic"],
    bio: "Kenji advises apple and highland vegetable growers in Nagano prefecture on biological management adapted to volcanic ash soils and heavy snow-load rotations. He consults remotely in English and Japanese.",
  },
  {
    id: "p19", slug: "gabriela-ortiz", displayName: "Gabriela Ortiz",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2023 }], certifiedSince: 2023,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 100,
    city: "Oaxaca", adminArea: "Oaxaca", countryCode: "MX", lat: 17.073, lng: -96.727,
    ecoregion: "Sierra Madre de Oaxaca pine-oak forests", biome: TMF, realm: "Neotropic",
    crops: ["tropical_smallholder", "coffee", "cereals"], soilTypes: ["clay", "volcanic"],
    languages: [{ slug: "es", proficiency: "native" }, { slug: "en", proficiency: "working" }],
    practices: ["microscopy", "compost_production"],
    bio: "Gabriela works with milpa smallholders and shade-coffee cooperatives in the Oaxacan highlands, pairing microscope assessment with compost programmes built on coffee pulp and local feedstocks.",
  },
  {
    id: "p20", slug: "stefan-brandt", displayName: "Stefan Brandt",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2020 }], certifiedSince: 2020,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 200,
    city: "Freiburg", adminArea: "Baden-Württemberg", countryCode: "DE", lat: 47.999, lng: 7.842,
    ecoregion: "Western European broadleaf forests", biome: TBF, realm: "Palearctic",
    crops: ["vineyard", "orchard_fruit", "vegetables"], soilTypes: ["loam", "calcareous"],
    languages: [{ slug: "de", proficiency: "native" }, { slug: "en", proficiency: "fluent" }, { slug: "fr", proficiency: "working" }],
    practices: ["microscopy", "compost_extracts"],
    bio: "Stefan assesses soils for Baden's steep-slope vineyards and Lake Constance orchards, and takes shipped samples from across the German-speaking countries.",
  },
  {
    id: "p21", slug: "nadia-haddad", displayName: "Nadia Haddad",
    roles: ["consultant", "lab_tech"], certifications: [{ program: "CC", year: 2023 }, { program: "LT", year: 2021 }], certifiedSince: 2021,
    acceptingClients: true, servicesRemotely: true, travelRadiusKm: 300,
    city: "Sousse", adminArea: "Sousse", countryCode: "TN", lat: 35.826, lng: 10.637,
    ecoregion: "Mediterranean dry woodlands and steppe", biome: MED, realm: "Palearctic",
    crops: ["olive", "cereals", "vegetables"], soilTypes: ["calcareous", "saline", "sandy"],
    languages: [{ slug: "fr", proficiency: "native" }, { slug: "en", proficiency: "working" }],
    practices: ["microscopy", "compost_production", "transition_organic"],
    bio: "Nadia combines lab assessment with field consulting for Tunisian olive estates and irrigated vegetable operations, with deep experience in saline irrigation water and gypsum-amended soils. She works across the Maghreb in French and Arabic.",
  },
  {
    id: "p22", slug: "will-thompson", displayName: "Will Thompson",
    roles: ["lab_tech"], certifications: [{ program: "LT", year: 2022 }], certifiedSince: 2022,
    acceptingClients: true, servicesRemotely: false, travelRadiusKm: 400,
    city: "Christchurch", adminArea: "Canterbury", countryCode: "NZ", lat: -43.532, lng: 172.636,
    ecoregion: "Canterbury-Otago tussock grasslands", biome: TGS, realm: "Australasia",
    crops: ["pasture", "cereals", "vineyard"], soilTypes: ["loam", "sandy"],
    languages: [{ slug: "en", proficiency: "native" }],
    practices: ["microscopy", "compost_production"],
    bio: "Will services Canterbury's mixed arable and dairy operations plus Waipara vineyards, driving the length of the South Island for sampling rounds each season.",
  },
];

export function bySlug(slug: string): Practitioner | undefined {
  return PRACTITIONERS.find((p) => p.slug === slug);
}
